name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  repo:
    name: deno ${{ matrix.deno }} / ${{ matrix.repo }}

    runs-on: ubuntu-20.04
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        deno: ['v1', 'canary']
        repo: ['nestdotland/nest', 'denoland/deno', 'nodejs/node']

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: ${{ matrix.repo }}
        run: deno run -A ./ghlog.ts '${{ matrix.repo }}'

  example:
    name: deno ${{ matrix.deno }} / ${{ matrix.example }}

    runs-on: ubuntu-20.04
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        deno: ['v1', 'canary']
        example: ['basic.ts', 'deno.ts', 'yargs.ts']

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: ${{ matrix.repo }}
        run: deno run -A ./examples/'${{ matrix.example }}'
